namespace BandwidthCalculator.Web.Models;

public static class FieldGuidance
{
    private const string TypicalChoiceGuidance = " A • marks a typical choice in this list.";

    public const string Resolution = "Sets width and height together from a recognised display mode. Full HD, QHD and 4K UHD are typical current desktop choices. Apple hardware entries include current MacBook, iMac, Studio Display and Pro Display XDR panel rasters, and set their known physical diagonal automatically; the historical 21.5-inch Retina 4K iMac is also included. Apple's Vision Pro modes are virtual: 6720×2880 is 21:9 Wide and 10240×2880 is 32:9 Ultrawide, so neither changes the physical diagonal." + TypicalChoiceGuidance;
    public const string Width = "The active horizontal pixel count, excluding blanking. Modern displays commonly range from 1,920 to 3,840 pixels; lower values are increasingly legacy and widths above 5,120 are still specialised. With the ratio locked, editing width recalculates height; unlocked, it preserves height and derives the exact ratio.";
    public const string Height = "The active vertical line count, excluding blanking. Typical current values are 1,080, 1,440 and 2,160 lines; 720 is now largely entry-level or legacy, while 2,880 and 4,320 remain premium. With the ratio locked, editing height recalculates width; unlocked, it preserves width and derives the exact ratio.";
    public const string AspectRatio = "The exact active-image width-to-height proportion. 16:9 is typical, 16:10 and 21:9 are common alternatives, and 4:3 is mainly legacy. Lock it to preserve this proportion when editing pixel dimensions; unlock it to preserve the other pixel dimension and derive a new ratio. Editing a ratio part always recalculates its matching pixel dimension.";
    public const string DisplayDiagonal = "The physical corner-to-corner length of the active display area, entered in inches or centimetres. It describes viewing geometry only and does not change bandwidth. A preset for identified hardware sets its published diagonal automatically; generic resolutions preserve your value because the same raster appears at many sizes. Laptop panels are commonly 13–16 inches, desktop monitors 24–32 inches, and televisions are often larger. Virtual displays such as Apple Vision Pro have no fixed physical diagonal.";
    public const string PixelDensity = "Pixels per inch across the physical display. Editing it preserves the current diagonal and aspect ratio, then resizes width and height to the nearest whole pixels; changing that pixel raster also changes bandwidth. Typical desktop monitors are often around 90–160 ppi; Apple desktop Retina displays are around 218 ppi, current MacBook Air panels around 224 ppi and MacBook Pro panels around 254 ppi.";
    public const string RefreshRate = "How many display frames or fields are requested each second. 60–120 Hz is typical for general display use and 144–240 Hz is common for gaming. Rates such as 24/23.976, 25/50 and 29.97/30 Hz are current format- and region-specific cinema, broadcast and OTA television cadences—not legacy rates. Very high rates depend on the complete signal chain.";
    public const string ColorDepth = "Bits used for each colour component before chroma subsampling. 8-bit is the established baseline and 10-bit is typical for HDR or colour-sensitive work; 12-bit and above are specialised, while 6-bit is legacy or uses temporal dithering." + TypicalChoiceGuidance;
    public const string ColorEncoding = "The colour representation carried by the signal. RGB is typical for computer monitors and preserves direct component values; YCbCr is common in television and video pipelines and enables chroma subsampling. Both are current." + TypicalChoiceGuidance;
    public const string ChromaSampling = "How much colour-detail resolution is retained relative to luma. 4:4:4 is typical for desktop text, 4:2:2 is common in production video, and 4:2:0 is common for delivery video but can soften coloured text. RGB is always 4:4:4." + TypicalChoiceGuidance;
    public const string TimingStandard = "The rule used to add blanking and derive the pixel clock. CVT-RBv2 is typical for modern computer displays; CTA timings are typical for televisions, DMT covers established PC modes, RBv1 is older, and RBv3/CTA OVT are newer with less universal adoption." + TypicalChoiceGuidance;
    public const string ScanMode = "Progressive sends every line each frame and is typical for modern displays. Interlaced sends alternating fields, is retained for legacy broadcast timings, and is rarely appropriate for new computer-display modes." + TypicalChoiceGuidance;
    public const string RefreshConvention = "Controls exact versus 1000/1001 rates such as 23.976, 29.97 and 59.94 Hz. Automatic is typical and recognises standard video rates; Exact is useful for computer timings, while 1000/1001 remains a current cinema, broadcast and video convention with historical television roots." + TypicalChoiceGuidance;
    public const string StandardTimingId = "Selects one exact VESA DMT identifier or CTA Video Identification Code. Use the ID published by the source/display standard; IDs are established rather than legacy, but not every device implements every listed mode.";
    public const string RbV3HorizontalBlank = "The CVT-RBv3 horizontal blanking interval. The standard permits 80–200 pixels in 8-pixel steps; 80 is the compact default. RBv3 is current but not yet as broadly adopted as RBv2.";
    public const string RbV3VerticalBlank = "The minimum CVT-RBv3 vertical blanking time. The supported standard range is 300–920 microseconds and 460 µs is a practical default. RBv3 remains less widely adopted than RBv2.";
    public const string RbV3EarlyVsync = "Moves vertical sync earlier within the RBv3 blanking interval for compatible sink timing. Leave off unless the target requires it; RBv3 and this option are not yet universally supported.";
    public const string ExactTargets = "Switches from theoretical reference profiles to one declared capability set per transport. Leave off for the simple estimate; enable only when negotiated rates, lanes and format features are known.";
    public const string DisplayPortRate = "The highest DisplayPort link rate negotiated by the target. HBR2/HBR3 are common, UHBR rates require DisplayPort 2.x hardware and are still less broadly deployed, while RBR/HBR are legacy.";
    public const string DisplayPortLanes = "The number of DisplayPort main-link lanes available. Four lanes are typical for a dedicated connection; one or two lanes are used by constrained or shared links and reduce payload proportionally.";
    public const string Dsc = "Display Stream Compression support. DSC is a current visually lossless transport option, but support must exist at both endpoints and can vary by mode; older devices may not implement it.";
    public const string Supports420 = "Allows 4:2:0 chroma transport. It is common for television/video modes and can reduce link demand, but it is not ideal for desktop text and is not supported by every link path.";
    public const string HdmiTransport = "Chooses legacy TMDS-only transport or HDMI Fixed Rate Link with TMDS fallback. FRL is typical for higher-bandwidth HDMI 2.1+ modes; TMDS remains current for lower modes but is the older transport.";
    public const string HdmiRate = "The maximum HDMI transport rate actually available. 18 Gbps TMDS and 40/48 Gbps FRL are common capability ceilings; HDMI 2.2 rates above 48 Gbps are new and not yet broadly adopted.";
    public const string DeepColor = "Allows HDMI colour depths above 8 bits per component. It is common on modern HDMI displays but still mode-dependent; disabling it models older or restricted TMDS equipment.";
    public const string AltModeRate = "The DisplayPort link rate negotiated through USB-C Alt Mode. HBR2/HBR3 are common; UHBR requires newer hosts, cables and sinks and remains less universally adopted.";
    public const string AltModeLanes = "USB-C can allocate two DisplayPort lanes while retaining USB 3 data, or four lanes for maximum video payload. Two lanes plus USB 3 is a common dock configuration; four lanes can displace high-speed USB data.";
}
